#!/bin/bash

# Generated by retold-manager/bin/manifest-rebuild-shell.js — do not hand-edit.
# Source of truth: Retold-Modules-Manifest.json at the repo root.

echo "### Building list of modules..."

repositoriesFable=("fable" "fable-log" "fable-log-logger-bunyan" "fable-serviceproviderbase" "fable-settings" "fable-uuid" "fable-ultravisor-client" "ultravisor-beacon" "ultravisor-beacon-capability")

repositoriesMeadow=("bibliograph" "bibliograph-storage-meadow" "foxhound" "meadow" "meadow-connection-dgraph" "meadow-connection-manager" "meadow-connection-mongodb" "meadow-connection-mssql" "meadow-connection-mysql" "meadow-connection-postgresql" "meadow-connection-rocksdb" "meadow-connection-retold-databeacon" "meadow-connection-solr" "meadow-connection-sqlite" "meadow-connection-sqlite-browser" "meadow-endpoints" "meadow-graph-client" "meadow-integration" "meadow-migrationmanager" "meadow-provider-offline" "parime" "retold-data-service" "retold-harness" "retold-harness-consistency-proxy" "stricture")

repositoriesOrator=("orator" "orator-authentication" "orator-conversion" "orator-endpoint" "orator-http-proxy" "orator-serviceserver-base" "orator-serviceserver-restify" "orator-ssl-proxy" "orator-static-server" "tidings")

repositoriesPict=("cryptbrau" "informary" "pict" "pict-application" "pict-docuserve" "pict-editor-timeline" "pict-meadow-connection-manager" "pict-nonlinearconfig" "pict-panel" "pict-provider" "pict-provider-vocabulary" "pict-router" "pict-section-code" "pict-section-connection-form" "pict-section-content" "pict-section-entitymanagement" "pict-section-equation" "pict-section-flow" "pict-section-form" "pict-section-formeditor" "pict-section-histogram" "pict-section-inlinedocumentation" "pict-section-login" "pict-section-markdowneditor" "pict-section-modal" "pict-section-objecteditor" "pict-section-openseadragon" "pict-section-recordset" "pict-section-tuigrid" "pict-section-usermanagement" "pict-service-commandlineutility" "pict-serviceproviderbase" "pict-sessionmanager" "pict-template" "pict-template-preprocessor" "pict-terminalui" "pict-view")

repositoriesUtility=("cachetrax" "choreographic" "cumulation" "elucidator" "indoctrinate" "manyfest" "manyfest-conversion" "merquerial" "pict-cruisecontrol" "precedent" "quackage" "retold-sample-data" "retold-sharp")

repositoriesApps=("retold-beacon-host" "retold-content-system" "retold-databeacon" "retold-data-mapper" "retold-facto" "retold-remote" "retold-remote-desktop" "retold-remote-ios" "ultravisor" "ultravisor-auth-beacon" "ultravisor-file-stream" "ultravisor-lab" "ultravisor-manifest-beacon" "ultravisor-queue-beacon" "ultravisor-suite-harness")

echo "### ... Module lists built!"
